package com.weboot.springboot.domain;

import java.util.Date;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MENU_ID
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.MENU_NAME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.PARENT_MENU_ID
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String parentMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.TYPE
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ACTION
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.CREATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.UPDATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MENU_ID
     *
     * @return the value of menu.MENU_ID
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MENU_ID
     *
     * @param menuId the value for menu.MENU_ID
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.MENU_NAME
     *
     * @return the value of menu.MENU_NAME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.MENU_NAME
     *
     * @param menuName the value for menu.MENU_NAME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.PARENT_MENU_ID
     *
     * @return the value of menu.PARENT_MENU_ID
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getParentMenuId() {
        return parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.PARENT_MENU_ID
     *
     * @param parentMenuId the value for menu.PARENT_MENU_ID
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setParentMenuId(String parentMenuId) {
        this.parentMenuId = parentMenuId == null ? null : parentMenuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.TYPE
     *
     * @return the value of menu.TYPE
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.TYPE
     *
     * @param type the value for menu.TYPE
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ACTION
     *
     * @return the value of menu.ACTION
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ACTION
     *
     * @param action the value for menu.ACTION
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.CREATE_TIME
     *
     * @return the value of menu.CREATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.CREATE_TIME
     *
     * @param createTime the value for menu.CREATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.UPDATE_TIME
     *
     * @return the value of menu.UPDATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.UPDATE_TIME
     *
     * @param updateTime the value for menu.UPDATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}