package com.weboot.springboot.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PathExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public PathExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPathIdIsNull() {
            addCriterion("PATH_ID is null");
            return (Criteria) this;
        }

        public Criteria andPathIdIsNotNull() {
            addCriterion("PATH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPathIdEqualTo(String value) {
            addCriterion("PATH_ID =", value, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdNotEqualTo(String value) {
            addCriterion("PATH_ID <>", value, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdGreaterThan(String value) {
            addCriterion("PATH_ID >", value, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdGreaterThanOrEqualTo(String value) {
            addCriterion("PATH_ID >=", value, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdLessThan(String value) {
            addCriterion("PATH_ID <", value, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdLessThanOrEqualTo(String value) {
            addCriterion("PATH_ID <=", value, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdLike(String value) {
            addCriterion("PATH_ID like", value, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdNotLike(String value) {
            addCriterion("PATH_ID not like", value, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdIn(List<String> values) {
            addCriterion("PATH_ID in", values, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdNotIn(List<String> values) {
            addCriterion("PATH_ID not in", values, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdBetween(String value1, String value2) {
            addCriterion("PATH_ID between", value1, value2, "pathId");
            return (Criteria) this;
        }

        public Criteria andPathIdNotBetween(String value1, String value2) {
            addCriterion("PATH_ID not between", value1, value2, "pathId");
            return (Criteria) this;
        }

        public Criteria andHttpPathIsNull() {
            addCriterion("HTTP_PATH is null");
            return (Criteria) this;
        }

        public Criteria andHttpPathIsNotNull() {
            addCriterion("HTTP_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andHttpPathEqualTo(String value) {
            addCriterion("HTTP_PATH =", value, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathNotEqualTo(String value) {
            addCriterion("HTTP_PATH <>", value, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathGreaterThan(String value) {
            addCriterion("HTTP_PATH >", value, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathGreaterThanOrEqualTo(String value) {
            addCriterion("HTTP_PATH >=", value, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathLessThan(String value) {
            addCriterion("HTTP_PATH <", value, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathLessThanOrEqualTo(String value) {
            addCriterion("HTTP_PATH <=", value, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathLike(String value) {
            addCriterion("HTTP_PATH like", value, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathNotLike(String value) {
            addCriterion("HTTP_PATH not like", value, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathIn(List<String> values) {
            addCriterion("HTTP_PATH in", values, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathNotIn(List<String> values) {
            addCriterion("HTTP_PATH not in", values, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathBetween(String value1, String value2) {
            addCriterion("HTTP_PATH between", value1, value2, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpPathNotBetween(String value1, String value2) {
            addCriterion("HTTP_PATH not between", value1, value2, "httpPath");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeIsNull() {
            addCriterion("HTTP_METHOD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeIsNotNull() {
            addCriterion("HTTP_METHOD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeEqualTo(String value) {
            addCriterion("HTTP_METHOD_TYPE =", value, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeNotEqualTo(String value) {
            addCriterion("HTTP_METHOD_TYPE <>", value, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeGreaterThan(String value) {
            addCriterion("HTTP_METHOD_TYPE >", value, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeGreaterThanOrEqualTo(String value) {
            addCriterion("HTTP_METHOD_TYPE >=", value, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeLessThan(String value) {
            addCriterion("HTTP_METHOD_TYPE <", value, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeLessThanOrEqualTo(String value) {
            addCriterion("HTTP_METHOD_TYPE <=", value, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeLike(String value) {
            addCriterion("HTTP_METHOD_TYPE like", value, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeNotLike(String value) {
            addCriterion("HTTP_METHOD_TYPE not like", value, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeIn(List<String> values) {
            addCriterion("HTTP_METHOD_TYPE in", values, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeNotIn(List<String> values) {
            addCriterion("HTTP_METHOD_TYPE not in", values, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeBetween(String value1, String value2) {
            addCriterion("HTTP_METHOD_TYPE between", value1, value2, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andHttpMethodTypeNotBetween(String value1, String value2) {
            addCriterion("HTTP_METHOD_TYPE not between", value1, value2, "httpMethodType");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table path
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 19 22:38:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}