package com.weboot.springboot.domain;

import java.util.Date;

public class Path {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.PATH_ID
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String pathId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.HTTP_PATH
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String httpPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.HTTP_METHOD_TYPE
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String httpMethodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.DESCRIPTION
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.TYPE
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.CREATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path.UPDATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.PATH_ID
     *
     * @return the value of path.PATH_ID
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.PATH_ID
     *
     * @param pathId the value for path.PATH_ID
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setPathId(String pathId) {
        this.pathId = pathId == null ? null : pathId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.HTTP_PATH
     *
     * @return the value of path.HTTP_PATH
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getHttpPath() {
        return httpPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.HTTP_PATH
     *
     * @param httpPath the value for path.HTTP_PATH
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setHttpPath(String httpPath) {
        this.httpPath = httpPath == null ? null : httpPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.HTTP_METHOD_TYPE
     *
     * @return the value of path.HTTP_METHOD_TYPE
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getHttpMethodType() {
        return httpMethodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.HTTP_METHOD_TYPE
     *
     * @param httpMethodType the value for path.HTTP_METHOD_TYPE
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setHttpMethodType(String httpMethodType) {
        this.httpMethodType = httpMethodType == null ? null : httpMethodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.DESCRIPTION
     *
     * @return the value of path.DESCRIPTION
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.DESCRIPTION
     *
     * @param description the value for path.DESCRIPTION
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.TYPE
     *
     * @return the value of path.TYPE
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.TYPE
     *
     * @param type the value for path.TYPE
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.CREATE_TIME
     *
     * @return the value of path.CREATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.CREATE_TIME
     *
     * @param createTime the value for path.CREATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path.UPDATE_TIME
     *
     * @return the value of path.UPDATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path.UPDATE_TIME
     *
     * @param updateTime the value for path.UPDATE_TIME
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}