package com.weboot.springboot.domain;

public class PermPathKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm_path.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String permId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm_path.PATH_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String pathId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm_path.PERM_ID
     *
     * @return the value of perm_path.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm_path.PERM_ID
     *
     * @param permId the value for perm_path.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setPermId(String permId) {
        this.permId = permId == null ? null : permId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm_path.PATH_ID
     *
     * @return the value of perm_path.PATH_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm_path.PATH_ID
     *
     * @param pathId the value for perm_path.PATH_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setPathId(String pathId) {
        this.pathId = pathId == null ? null : pathId.trim();
    }
}