package com.weboot.springboot.domain;

import java.util.Date;

public class Perm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String permId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm.PERM_NAME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String permName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm.PARENT_PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String parentPermId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm.TYPE
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm.CREATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm.UPDATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm.DESCRIPTION
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm.PERM_ID
     *
     * @return the value of perm.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm.PERM_ID
     *
     * @param permId the value for perm.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setPermId(String permId) {
        this.permId = permId == null ? null : permId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm.PERM_NAME
     *
     * @return the value of perm.PERM_NAME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getPermName() {
        return permName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm.PERM_NAME
     *
     * @param permName the value for perm.PERM_NAME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setPermName(String permName) {
        this.permName = permName == null ? null : permName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm.PARENT_PERM_ID
     *
     * @return the value of perm.PARENT_PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getParentPermId() {
        return parentPermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm.PARENT_PERM_ID
     *
     * @param parentPermId the value for perm.PARENT_PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setParentPermId(String parentPermId) {
        this.parentPermId = parentPermId == null ? null : parentPermId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm.TYPE
     *
     * @return the value of perm.TYPE
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm.TYPE
     *
     * @param type the value for perm.TYPE
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm.CREATE_TIME
     *
     * @return the value of perm.CREATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm.CREATE_TIME
     *
     * @param createTime the value for perm.CREATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm.UPDATE_TIME
     *
     * @return the value of perm.UPDATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm.UPDATE_TIME
     *
     * @param updateTime the value for perm.UPDATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm.DESCRIPTION
     *
     * @return the value of perm.DESCRIPTION
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm.DESCRIPTION
     *
     * @param description the value for perm.DESCRIPTION
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}