package com.weboot.springboot.domain;

public class PermMenuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm_menu.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String permId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column perm_menu.MENU_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm_menu.PERM_ID
     *
     * @return the value of perm_menu.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm_menu.PERM_ID
     *
     * @param permId the value for perm_menu.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setPermId(String permId) {
        this.permId = permId == null ? null : permId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column perm_menu.MENU_ID
     *
     * @return the value of perm_menu.MENU_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column perm_menu.MENU_ID
     *
     * @param menuId the value for perm_menu.MENU_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }
}