package com.weboot.springboot.domain;

public class RolePermKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_perm.ROLE_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_perm.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String permId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_perm.ROLE_ID
     *
     * @return the value of role_perm.ROLE_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_perm.ROLE_ID
     *
     * @param roleId the value for role_perm.ROLE_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_perm.PERM_ID
     *
     * @return the value of role_perm.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_perm.PERM_ID
     *
     * @param permId the value for role_perm.PERM_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setPermId(String permId) {
        this.permId = permId == null ? null : permId.trim();
    }
}