package com.weboot.springboot.domain;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_NAME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.TYPE
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.CREATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.UPDATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.DESCRIPTION
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_ID
     *
     * @return the value of role.ROLE_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_ID
     *
     * @param roleId the value for role.ROLE_ID
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_NAME
     *
     * @return the value of role.ROLE_NAME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_NAME
     *
     * @param roleName the value for role.ROLE_NAME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.TYPE
     *
     * @return the value of role.TYPE
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.TYPE
     *
     * @param type the value for role.TYPE
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.CREATE_TIME
     *
     * @return the value of role.CREATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.CREATE_TIME
     *
     * @param createTime the value for role.CREATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.UPDATE_TIME
     *
     * @return the value of role.UPDATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.UPDATE_TIME
     *
     * @param updateTime the value for role.UPDATE_TIME
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.DESCRIPTION
     *
     * @return the value of role.DESCRIPTION
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.DESCRIPTION
     *
     * @param description the value for role.DESCRIPTION
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}