package com.weboot.springboot.domain;

public class UserPathKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_path.USER_ID
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_path.PATH_ID
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    private String pathId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_path.USER_ID
     *
     * @return the value of user_path.USER_ID
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_path.USER_ID
     *
     * @param userId the value for user_path.USER_ID
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_path.PATH_ID
     *
     * @return the value of user_path.PATH_ID
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    public String getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_path.PATH_ID
     *
     * @param pathId the value for user_path.PATH_ID
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    public void setPathId(String pathId) {
        this.pathId = pathId == null ? null : pathId.trim();
    }
}