package com.weboot.springboot.model;

import java.util.Date;

public class Org {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_ID
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.PARENT_ORG_ID
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    private String parentOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_NAME
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_NUMBER
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    private String orgNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.STATUS
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.CREATE_TIME
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.UPDATE_TIME
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_ID
     *
     * @return the value of sys_org.ORG_ID
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_ID
     *
     * @param orgId the value for sys_org.ORG_ID
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.PARENT_ORG_ID
     *
     * @return the value of sys_org.PARENT_ORG_ID
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public String getParentOrgId() {
        return parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.PARENT_ORG_ID
     *
     * @param parentOrgId the value for sys_org.PARENT_ORG_ID
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public void setParentOrgId(String parentOrgId) {
        this.parentOrgId = parentOrgId == null ? null : parentOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_NAME
     *
     * @return the value of sys_org.ORG_NAME
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_NAME
     *
     * @param orgName the value for sys_org.ORG_NAME
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_NUMBER
     *
     * @return the value of sys_org.ORG_NUMBER
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public String getOrgNumber() {
        return orgNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_NUMBER
     *
     * @param orgNumber the value for sys_org.ORG_NUMBER
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public void setOrgNumber(String orgNumber) {
        this.orgNumber = orgNumber == null ? null : orgNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.STATUS
     *
     * @return the value of sys_org.STATUS
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.STATUS
     *
     * @param status the value for sys_org.STATUS
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.CREATE_TIME
     *
     * @return the value of sys_org.CREATE_TIME
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.CREATE_TIME
     *
     * @param createTime the value for sys_org.CREATE_TIME
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.UPDATE_TIME
     *
     * @return the value of sys_org.UPDATE_TIME
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.UPDATE_TIME
     *
     * @param updateTime the value for sys_org.UPDATE_TIME
     *
     * @mbg.generated Thu Jan 16 15:18:59 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}