package com.weboot.springboot.mapper;

import com.weboot.springboot.domain.Menu;
import com.weboot.springboot.domain.MenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    long countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    Menu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByPrimaryKey(Menu record);
}