package com.weboot.springboot.mapper;

import com.weboot.springboot.domain.Path;
import com.weboot.springboot.domain.PathExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    long countByExample(PathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    int deleteByExample(PathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    int deleteByPrimaryKey(String pathId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    int insert(Path record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    int insertSelective(Path record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    List<Path> selectByExample(PathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    Path selectByPrimaryKey(String pathId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") Path record, @Param("example") PathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    int updateByExample(@Param("record") Path record, @Param("example") PathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    int updateByPrimaryKeySelective(Path record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table path
     *
     * @mbg.generated Sun Jan 19 22:38:47 CST 2020
     */
    int updateByPrimaryKey(Path record);
}