package com.weboot.springboot.mapper;

import com.weboot.springboot.domain.Perm;
import com.weboot.springboot.domain.PermExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    long countByExample(PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByExample(PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByPrimaryKey(String permId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insert(Perm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insertSelective(Perm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    List<Perm> selectByExample(PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    Perm selectByPrimaryKey(String permId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") Perm record, @Param("example") PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExample(@Param("record") Perm record, @Param("example") PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByPrimaryKeySelective(Perm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByPrimaryKey(Perm record);
}