package com.weboot.springboot.mapper;

import com.weboot.springboot.domain.PermMenuExample;
import com.weboot.springboot.domain.PermMenuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    long countByExample(PermMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByExample(PermMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByPrimaryKey(PermMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insert(PermMenuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insertSelective(PermMenuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    List<PermMenuKey> selectByExample(PermMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") PermMenuKey record, @Param("example") PermMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_menu
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExample(@Param("record") PermMenuKey record, @Param("example") PermMenuExample example);
}