package com.weboot.springboot.mapper;

import com.weboot.springboot.domain.PermPathExample;
import com.weboot.springboot.domain.PermPathKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_path
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    long countByExample(PermPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_path
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByExample(PermPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_path
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByPrimaryKey(PermPathKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_path
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insert(PermPathKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_path
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insertSelective(PermPathKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_path
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    List<PermPathKey> selectByExample(PermPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_path
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") PermPathKey record, @Param("example") PermPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm_path
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExample(@Param("record") PermPathKey record, @Param("example") PermPathExample example);
}