package com.weboot.springboot.mapper;

import com.weboot.springboot.domain.RolePermExample;
import com.weboot.springboot.domain.RolePermKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    long countByExample(RolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByExample(RolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int deleteByPrimaryKey(RolePermKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insert(RolePermKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int insertSelective(RolePermKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    List<RolePermKey> selectByExample(RolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolePermKey record, @Param("example") RolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_perm
     *
     * @mbg.generated Fri Feb 07 23:22:04 CST 2020
     */
    int updateByExample(@Param("record") RolePermKey record, @Param("example") RolePermExample example);
}