package com.weboot.springboot.mapper;

import com.weboot.springboot.domain.UserPathExample;
import com.weboot.springboot.domain.UserPathKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_path
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    long countByExample(UserPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_path
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    int deleteByExample(UserPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_path
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    int deleteByPrimaryKey(UserPathKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_path
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    int insert(UserPathKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_path
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    int insertSelective(UserPathKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_path
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    List<UserPathKey> selectByExample(UserPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_path
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserPathKey record, @Param("example") UserPathExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_path
     *
     * @mbg.generated Tue Feb 04 10:51:26 CST 2020
     */
    int updateByExample(@Param("record") UserPathKey record, @Param("example") UserPathExample example);
}